name: supertab-xg
channels:
- conda-forge
dependencies:
- jupyter>=1.0
- jupyterlab>=1.2
- matplotlib=3.1.*
- nbstripout=0.3.*
- numpy=1.17.*
- pandas=0.25.*
- python=3.7.*
- plotly=4.2.*
- pytz>=2019.*
- nb_conda>=2.2
- nb_conda_kernels>=2.2
- seaborn=0.9.*
- scikit-learn=0.21.*
- bokeh=1.3.*
- click=7.*
- pytest=5.2.*
- mysql-connector-python=8.0.*
- pytables=3.6.*
- xlrd=1.2.*
- hyperopt=0.2.*
- pytorch=1.4.*
- category_encoders
- pyarrow
- pip
- pip:
  - black
  - xgboost
  - mlflow
  - isort
  - colorama
  - jrnl
  - jupyter_contrib_nbextensions